### ISSUE TITLE
[BUG] - Lidarr - Beets Broken releasetype

### ISSUE THREAD

**Issue by Blindie92** [RandomNinjaAtk/arr-scripts#170] opened 2024-01-28 16:16 UTC
**Application**
Lidarr

**Host platform**
Truenas/Docker

**Script**
Beets Tagging

**Script Version**
1.8

**Describe the bug**
The Album Releastype tag is broken, each character have his own tag, described here https://github.com/beetbox/beets/issues/4528 it looks like the bug is fixed, but not implemented here?

**To Reproduce**
1. Download some music
2. look at the Taggs with software like Picard

**Expected behavior**
The releastype should be in one tag, seperated with ; like in musicbrainz

**Logs/Screenshots**
![grafik](https://github.com/RandomNinjaAtk/arr-scripts/assets/94938390/3f938ecf-82a5-446c-968e-f1cf37784e2b)

**Additional context**
the bug is described here https://github.com/beetbox/beets/issues/4528

**Comment by RandomNinjaAtk** [comment] 2024-01-28 17:20
Beets is installed using the alpine package, so if its fixed in beets, the alpine package needs to be updated... Nothing to do on this end other than waiting for an updated package or possibly consider installing beets via a different method...

**Comment by RandomNinjaAtk** [comment] 2024-02-01 11:25
Switching to the pip package does not seem to solve the issue. So the problem is the upstream packages are not updated... It should resolve itself when those get updated, so there is nothing to do here....  If you know of a way to resolve it now, I'll gladly review a PR.

**Closed by RandomNinjaAtk** 2024-02-01 11:25 UTC
Labels: lidarr
