### ISSUE TITLE
PlexNotify not working

### ISSUE THREAD

**Issue by cgram23** [RandomNinjaAtk/arr-scripts#54] opened 2023-08-07 16:44 UTC
I've been pounding my head on this for a week, and I can't seem to figure it out.  I've set all of my paths according to Trash's suggestions, so both Plex and Sonarr have /data/media/dvr set for my tv shows.  However, when a new show imports, all I see in the logs are:

08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Plex Connection Established, version: 1.32.6.7371-b6a09ad81
08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Sonarr :: ERROR: No Plex Library found containing path "/data/media/dvr"
08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Sonarr :: ERROR: Add "/data/media/dvr" as a folder to a Plex Movie Library

Sonarr and Plex are dockers running on Unraid, and both have identical directory mappings, so I have no idea what the issue might be.  Any help would be appreciated.

**Comment by cgram23** [comment] 2023-08-07 16:47
Also, I have set everything up per your instructions, so all packages are being installed from the setup script.

**Comment by RandomNinjaAtk** [comment] 2023-08-07 16:51
Did you verify your Plex library has the correct path mapped? Not the container, but in plex itself.... just like the error says...

`ERROR: Add "/data/media/dvr" as a folder to a Plex TV Library`

**Comment by cgram23** [comment] 2023-08-07 16:55
Thanks for the reply.  Yea....it's set just like that in Plex.  

<img width="721" alt="Screenshot 2023-08-07 at 12 55 09 PM" src="https://github.com/RandomNinjaAtk/arr-scripts/assets/8229923/15125894-246d-4935-af97-af46ebffce4c">

**Comment by cgram23** [comment] 2023-08-07 17:16
Hmm.  I ran a manual curl command using the values in the .conf file, and it seems to come back normal.  I can't see anything out of the ordinary here.

![Screenshot 2023-08-07 at 1 15 42 PM](https://github.com/RandomNinjaAtk/arr-scripts/assets/8229923/d0600e04-e469-4203-aa85-d56506624367)

**Comment by RandomNinjaAtk** [comment] 2023-08-07 17:27
You need to take the curl command and pipe it, just like the second command to see what you find.

`curl command | xq ".MediaContainer.Directory"`

That data is used to look for the folder...

**Comment by RandomNinjaAtk** [comment] 2023-08-07 17:46
Really not sure, looks fine, however I made a small tweak to see if that could help... It's untested, but give it a try. You'll need to verify it actually works. If it does, I should probably make that change to the other container scripts...

Reference: https://github.com/RandomNinjaAtk/arr-scripts/commit/2892856885fdd9ae89cca7d70c8ba5a0e0f484f4

**Comment by cgram23** [comment] 2023-08-07 17:52
Ok....will try in out.  

And thanks for the help!

**Comment by cgram23** [comment] 2023-08-07 21:03
FYI....I just tried the updated script, and no luck.

**Comment by RandomNinjaAtk** [comment] 2023-08-07 21:24
Same error?

**Comment by cgram23** [comment] 2023-08-07 22:15
yep...exactly the same

**Comment by RandomNinjaAtk** [comment] 2023-08-07 22:19
Welp, then IDK, you'd have to do more local debugging. It's not reproducible in my own setup... The latest changes and original script all work in my configuration.

I'm also on unraid... Using Linuxserver Plex container and Linuxserver Sonarr....

**Comment by justinglock40** [comment] 2023-08-08 17:45
> I've been pounding my head on this for a week, and I can't seem to figure it out. I've set all of my paths according to Trash's suggestions, so both Plex and Sonarr have /data/media/dvr set for my tv shows. However, when a new show imports, all I see in the logs are:
> 
> 08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Plex Connection Established, version: 1.32.6.7371-b6a09ad81 08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Sonarr :: ERROR: No Plex Library found containing path "/data/media/dvr" 08/07/2023 16:14:56 - Standard - 2023-08-07 12:14:56 :: PlexNotify :: 1.0.2 :: Sonarr :: ERROR: Add "/data/media/dvr" as a folder to a Plex Movie Library
> 
> Sonarr and Plex are dockers running on Unraid, and both have identical directory mappings, so I have no idea what the issue might be. Any help would be appreciated.

If it's a new library. You can try adding one thing to it and run a complete library scan on it. and if you are using more than one Plex instance make sure you're point to the right one.

**Comment by RandomNinjaAtk** [comment] 2023-08-14 14:56
Closing because I cannot replicate the problem.... If you find a solution via more debugging, please post it here and re-open so it can be addressed possibly.

**Closed by RandomNinjaAtk** 2023-08-14 14:56 UTC
Labels: Not Reproducible, User Error, sonarr, unraid (host)
