### ISSUE TITLE
[FEATURE] - Updates Beets to 1.6.1 in Lidarr scripts

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [RandomNinjaAtk/arr-scripts#204] opened 2024-02-29 04:13 UTC
Beets development seems to have stopped some 3 years ago but there is a 1.6.1 branch that has a lot of updates, bug fixes, and new features. I am interested because I use the LRCLIB update to inject synchronised lyrics into the files rather than just plain text. It also provides more fields and data providers. Please see the change log 

https://docs.beets.io/en/latest/changelog.html

The bad news is that it is not available via pip (or at least not that I can see) so you would have to include it through another means. It is available in the linuxserver docker nightly https://github.com/linuxserver/docker-beets/tree/nightly

If I understood how docker files worked I would try and make it work but that is over my head at the moment.

**Comment by hockeygoalie35** [comment] 2024-02-29 04:28
I don't think its true that the docker build uses the 1.6.1 dev version. I'm guessing you did a google search for something like: "beets 1.6.1". It looks like it picks up 1.6.1  from the mp3gain package:

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/f90acf13-de35-40c2-acf3-ec229661d145)

**Comment by Intrinsically-Sublime** [comment] 2024-02-29 04:40
I am running the nightly one from Linuxserver separately and it is 1.6.1

docker exec -it beets beet version
beets version 1.6.1
Python version 3.11.8

**Comment by hockeygoalie35** [comment] 2024-02-29 04:51
Ah, I understand, my apolgies. Look towards the bottom of [this discussion](https://github.com/beetbox/beets/discussions/4501). Looks like a new release is imminent.

**Comment by hockeygoalie35** [comment] 2024-04-01 13:33
@Intrinsically-Sublime [Soon... ](https://github.com/beetbox/beets/discussions/4501#discussioncomment-8955500)👀

**Comment by hockeygoalie35** [comment] 2024-06-19 03:54
Looks like Beets 2.0 has been [released](https://github.com/beetbox/beets/releases/tag/v2.0.0)!  I'm also intrested in using LRCLIB...I'll dig into it!

**Comment by hockeygoalie35** [comment] 2024-06-19 04:04
@RandomNinjaAtk , would it be as simple as adding:

To `beets-config.yaml`

```yaml
lyrics:
    auto: yes
    sources: lrclib genius tekstowo
    synced: yes

```

to `setup.bash`, add beautifulsoup4 to the pip install?


Beets Documentation [Reference](https://beets.readthedocs.io/en/stable/plugins/lyrics.html#configuration)

**Comment by hockeygoalie35** [comment] 2024-06-20 03:24
I can confirm that it worked! I made a fork with this setup (plus updating `beets-config-lidarr.yaml`), pushing a PR to implement.

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/7562408d-6de2-467f-8d94-0db5f99758d9)

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/95885642-4fee-40a3-b820-5abb4fd6b614)

**Comment by hockeygoalie35** [comment] 2024-06-20 03:57
@Intrinsically-Sublime  
>  I am interested because I use the LRCLIB update to inject synchronised lyrics into the files rather than just plain text.

Any chance you can show me how to do this on my existing library? This only works going forward, of course.

**Comment by Intrinsically-Sublime** [comment] 2024-06-20 05:09
@hockeygoalie35 I think you need to set the force flag to yes and then process the entire library https://beets.readthedocs.io/en/stable/plugins/lyrics.html
I imported my entire library using the newer version.

**Comment by hockeygoalie35** [comment] 2024-08-09 02:50
@Intrinsically-Sublime I think we're good here, it should be working as expected. Mind closing the issue?

**Closed** 2024-08-12 05:16 UTC
Labels: enhancement

**Comment by hockeygoalie35** [comment] 2025-01-04 17:16
@Intrinsically-Sublime 
Weirdly, when using beets myself, it of course writes the synced lyrics to the .flac as intended, but it's not getting the standalone .lrc file.... @RandomNinjaAtk just to confirm, you don't have anything that's grabbing .lrcs are you?
